export default `

----------------------------------------------------------------------------------------------------------------------
-- LECTURE 33

-- Parents
create table parents as
  select "abraham" as parent, "barack" as child union
  select "abraham"          , "clinton"         union
  select "delano"           , "herbert"         union
  select "fillmore"         , "abraham"         union
  select "fillmore"         , "delano"          union
  select "fillmore"         , "grover"          union
  select "eisenhower"       , "fillmore";

-- Arithmetic

create table lift as
  select 101 as chair, 2 as single, 2 as couple union
  select 102         , 0          , 3           union
  select 103         , 4          , 1;

-- Ints
create table ints as
  select "zero" as word, 0 as one, 0 as two, 0 as four, 0 as eight union
  select "one"         , 1       , 0       , 0        , 0          union
  select "two"         , 0       , 2       , 0        , 0          union
  select "three"       , 1       , 2       , 0        , 0          union
  select "four"        , 0       , 0       , 4        , 0          union
  select "five"        , 1       , 0       , 4        , 0          union
  select "six"         , 0       , 2       , 4        , 0          union
  select "seven"       , 1       , 2       , 4        , 0          union
  select "eight"       , 0       , 0       , 0        , 8          union
  select "nine"        , 1       , 0       , 0        , 8;

----------------------------------------------------------------------------------------------------------------------
-- Lecture 34

-- Grandparents
CREATE TABLE grandparents AS
    SELECT a.parent AS grandog, b.child AS granpup
      FROM parents AS a, parents AS b
      WHERE a.child = b.parent;

CREATE TABLE cities AS
    SELECT 38 AS latitude, 122 AS longitude, "Berkeley" AS name UNION
    SELECT 42,              71,              "Cambridge"        UNION
    SELECT 45,              93,              "Minneapolis"      UNION
    SELECT 33,             117,              "San Diego"        UNION
    SELECT 26,              80,              "Miami"            UNION
    SELECT 90,               0,              "North Pole";

CREATE TABLE cold AS
  SELECT name FROM cities WHERE latitude > 43 UNION
  SELECT "Chicago";

CREATE TABLE distances AS
SELECT a.name AS first, b.name AS second,
       69*(a.latitude-b.latitude) AS distance
       FROM cities AS a, cities AS b
       WHERE a.name != b.name
       ORDER BY a.longitude;

CREATE TABLE nouns AS
 SELECT "the dog" AS phrase UNION
 SELECT "the cat"           UNION
 SELECT "the bird";


CREATE TABLE ands AS
SELECT phrase FROM nouns UNION
SELECT first.phrase || " AND " || second.phrase
      FROM nouns AS first, nouns AS second
      WHERE first.phrase != second.phrase;

----------------------------------------------------------------------------------------------------------------------
-- Lecture 35

create table animals as
  select "dog" as kind, 4 as legs, 20 as weight union
  select "cat"        , 4        , 10           union
  select "ferret"     , 4        , 10           union
  select "parrot"     , 2        , 6            union
  select "penguin"    , 2        , 10           union
  select "t-rex"      , 2        , 12000;


----------------------------------------------------------------------------------------------------------------------
-- Hw 11

CREATE TABLE dogs AS
  SELECT "abraham" AS name, "long" AS fur, 26 AS height UNION
  SELECT "barack"         , "short"      , 52           UNION
  SELECT "clinton"        , "long"       , 47           UNION
  SELECT "delano"         , "long"       , 46           UNION
  SELECT "eisenhower"     , "short"      , 35           UNION
  SELECT "fillmore"       , "curly"      , 32           UNION
  SELECT "grover"         , "short"      , 28           UNION
  SELECT "herbert"        , "curly"      , 31;

CREATE TABLE sizes AS
  SELECT "toy" AS size, 24 AS min, 28 AS max UNION
  SELECT "mini"       , 28       , 35        UNION
  SELECT "medium"     , 35       , 45        UNION
  SELECT "standard"   , 45       , 60;

----------------------------------------------------------------------------------------------------------------------
-- Lab 12

CREATE TABLE students AS
   SELECT "4/19/2019 21:47:40" AS time, 17 AS number, "blue" AS color, "7" AS seven, "Crab Rave by Noisestorm" as song, "8/1" as date, "dog" as pet, "9 (Jacqueline Tiffany Yeung)" AS animal, 1 AS smallest UNION
   SELECT "4/19/2019 21:47:41", 69          , "red"                                          , "the number 7 below."       , "Never gonna give you up", "4/13" , "wolf"                                                                                                                                                              , "7 (Kevin Yu)", 8      UNION
   SELECT "4/19/2019 21:47:43", 91          , "black"                                        , "7"                         , "All I want for Christmas", "7/29" , "giraffe"                                                                                                                                                           , "3 (Tim Foster)", 55     UNION
   SELECT "4/19/2019 21:48:11", 73          , "blue"                                         , "7"                         , "Crab Rave"              , "4/20" , "uwu cats"                                                                                                                                                          , "5 (Chae Park)", 15     UNION
   SELECT "4/19/2019 21:48:30", 18          , "blue"                                         , "seven"                     , "All I want for Christmas", "9/18" , "tiger"                                                                                                                                                             , "4 (Chae Park)", 41     UNION
   SELECT "4/19/2019 21:49:08", 3           , "blue"                                         , "7"                         , "Shelter"                , "6/28" , "ferret"                                                                                                                                                            , "2 (Rachel De Jaen)", 1      UNION
   SELECT "4/19/2019 21:49:11", 69          , "greem"                                        , "Choose this option instead", "All Star"               , "6/4"  , "dragon"                                                                                                                                                            , "7 (Kevin Yu)", 37     UNION
   SELECT "4/19/2019 21:49:21", 99          , "red"                                          , "the number 7 below."       , "Big enough"             , "5/21" , "pikachu"                                                                                                                                                           , "7 (Kevin Yu)", 2      UNION
   SELECT "4/19/2019 21:49:22", 3           , "red"                                          , "7"                         , "Never gonna give you up", "1/1"  , "a labradoodle"                                                                                                                                                    , "5 (Chae Park)", 1      UNION
   SELECT "4/19/2019 21:49:27", 69          , "white"                                        , "the number 7 below."       , "All I want for Christmas", "11/11", "rat"                                                                                                                                                               , "4 (Chae Park)", 1      UNION
   SELECT "4/19/2019 21:49:36", 97          , "pink"                                         , "seven"                     , "All I want for Christmas", "6/7"  , "rabbit"                                                                                                                                                            , "1 (Karthik Bharathala)", 19     UNION
   SELECT "4/19/2019 21:49:37", 33          , "something dark"                               , "the number 7 below."       , "Never gonna give you up", "2/29" , "cat"                                                                                                                                                               , "2 (Rachel De Jaen)", 13     UNION
   SELECT "4/19/2019 21:50:09", 4           , "pink"                                         , "Choose this option instead", "All I want for Christmas", "3/4"  , "cat"                                                                                                                                                               , "4 (Chae Park)", 6      UNION
   SELECT "4/19/2019 21:50:39", 78          , "blue"                                         , "Choose this option instead", "All I want for Christmas", "1/5"  , "human"                                                                                                                                                             , "7 (Kevin Yu)", 1      UNION
   SELECT "4/19/2019 21:50:40", 2           , "red"                                          , "the number 7 below."       , "Never gonna give you up", "12/25", "guinea pig"                                                                                                                                                        , "6 (Rachel De Jaen catsits)", 6      UNION
   SELECT "4/19/2019 21:51:42", 14          , "i bleed blue and gold"                        , "7"                         , "All I want for Christmas", "5/9"  , "dog"                                                                                                                                                               , "9 (Jacqueline Tiffany Yeung)", 2      UNION
   SELECT "4/19/2019 21:52:00", 13          , "purple"                                       , "the number 7 below."       , "Never gonna give you up", "7/4"  , "otter"                                                                                                                                                             , "5 (Chae Park)", 739    UNION
   SELECT "4/19/2019 21:52:12", 69          , "oski brown"                                   , "the number 7 below."       , "Crab Rave"              , "4/20" , "john denero"                                                                                                                                                       , "9 (Jacqueline Tiffany Yeung)", 14     UNION
   SELECT "4/19/2019 21:52:42", 18          , "yellow"                                       , "the number 7 below."       , "Shelter"                , "3/18" , "jellyfish"                                                                                                                                                         , "4 (Chae Park)", 34     UNION
   SELECT "4/19/2019 21:53:19", 47          , "blue"                                         , "Choose this option instead", "Never gonna give you up", "11/10", "tiger"                                                                                                                                                             , "9 (Jacqueline Tiffany Yeung)", 2      UNION
   SELECT "4/19/2019 21:53:27", 14          , "white"                                        , "Choose this option instead", "All I want for Christmas", "1/1"  , "whale"                                                                                                                                                             , "9 (Jacqueline Tiffany Yeung)", 1      UNION
   SELECT "4/19/2019 21:53:43", 96          , "red"                                          , "the number 7 below."       , "All Star"               , "11/17", "cat"                                                                                                                                                               , "4 (Chae Park)", 1      UNION
   SELECT "4/19/2019 21:54:41", 9           , "blue"                                         , "7"                         , "All I want for Christmas", "8/1"  , "dog"                                                                                                                                                               , "7 (Kevin Yu)", 9      UNION
   SELECT "4/19/2019 21:55:22", 7           , "blue"                                         , "7"                         , "All I want for Christmas", "7/3"  , "tiger,panda"                                                                                                                                                       , "1 (Karthik Bharathala)", 1      UNION
   SELECT "4/19/2019 21:55:54", 98          , "blue"                                         , "7"                         , "All Star"               , "8/12" , "panda"                                                                                                                                                             , "4 (Chae Park)", 1      UNION
   SELECT "4/19/2019 21:56:03", 3           , "green"                                        , "7"                         , "All Star"               , "12/23", "penguins"                                                                                                                                                          , "4 (Chae Park)", 1      UNION
   SELECT "4/19/2019 21:57:11", 2           , "gray"                                         , "7"                         , "All I want for Christmas", "12/24", "golden retriever"                                                                                                                                                  , "7 (Kevin Yu)", 4      UNION
   SELECT "4/19/2019 22:00:04", 25          , "green"                                        , "7"                         , "All I want for Christmas", "4/6"  , "cat!"                                                                                                                                                              , "1 (Karthik Bharathala)", 1      UNION
   SELECT "4/19/2019 22:00:36", 1           , "white"                                        , "Choose this option instead", "Never gonna give you up", "11/3" , "dog"                                                                                                                                                               , "8 (Jade Singh)", 3      UNION
   SELECT "4/19/2019 22:01:07", 86          , "blue"                                         , "7"                         , "Never gonna give you up", "8/6"  , "mouse"                                                                                                                                                             , "7 (Kevin Yu)", 4      UNION
   SELECT "4/19/2019 22:01:30", 16          , "blue"                                         , "the number 7 below."       , "Never gonna give you up", "12/25", "doge"                                                                                                                                                              , "8 (Jade Singh)", 1      UNION
   SELECT "4/19/2019 22:01:50", 10          , "ted"                                          , "Choose this option instead", "All I want for Christmas", "10/1" , "dog"                                                                                                                                                               , "5 (Chae Park)", 1      UNION
   SELECT "4/19/2019 22:02:30", 42          , "black"                                        , "the number 7 below."       , "Shelter"                , "4/20" , "a clone of myself"                                                                                                                                                 , "3 (Tim Foster)", 42     UNION
   SELECT "4/19/2019 22:02:32", 99          , "red"                                          , "You're not the boss of me!", "Crab Rave"              , "11/26", "cat"                                                                                                                                                               , "6 (Rachel De Jaen catsits)", 30     UNION
   SELECT "4/19/2019 22:03:16", 66          , "transparent"                                  , "You're not the boss of me!", "Never gonna give you up", "4/20" , "mountain lion"                                                                                                                                                     , "2 (Rachel De Jaen)", 1      UNION
   SELECT "4/19/2019 22:04:06", 99          , "blue"                                         , "You're not the boss of me!", "All I want for Christmas", "6/1"  , "dog"                                                                                                                                                               , "7 (Kevin Yu)", 1      UNION
   SELECT "4/19/2019 22:05:19", 21          , "blue"                                         , "seven"                     , "Never gonna give you up", "5/22" , "wolf"                                                                                                                                                              , "4 (Chae Park)", 1      UNION
   SELECT "4/19/2019 22:06:09", 10          , "black"                                        , "the number 7 below."       , "All I want for Christmas", "2/29" , "lion"                                                                                                                                                              , "1 (Karthik Bharathala)", 9999999  UNION
   SELECT "4/19/2019 22:08:27", 69          , "pink"                                         , "7"                         , "Crab Rave"              , "4/20" , "cat"                                                                                                                                                               , "7 (Kevin Yu)", 46     UNION
   SELECT "4/19/2019 22:09:19", 88          , "green"                                        , "the number 7 below."       , "All I want for Christmas", "12/3" , "dragon"                                                                                                                                                            , "6 (Rachel De Jaen catsits)", 10000000  UNION
   SELECT "4/19/2019 22:09:49", 15          , "blue"                                         , "the number 7 below."       , "All I want for Christmas", "10/16", "hedgehog"                                                                                                                                                          , "4 (Chae Park)", 2      UNION
   SELECT "4/19/2019 22:10:30", 7           , "blue"                                         , "the number 7 below."       , "Shelter"                , "1/23" , "platypus"                                                                                                                                                          , "6 (Rachel De Jaen catsits)", 29     UNION
   SELECT "4/19/2019 22:11:54", 20          , "blue"                                         , "the number 7 below."       , "All I want for Christmas", "3/2"  , "cat"                                                                                                                                                               , "1 (Karthik Bharathala)", 1      UNION
   SELECT "4/19/2019 22:13:03", 69          , "blue"                                         , "the number 7 below."       , "Never gonna give you up", "9/3"  , "lion"                                                                                                                                                              , "9 (Jacqueline Tiffany Yeung)", 643    UNION
   SELECT "4/19/2019 22:13:07", 47          , "pink"                                         , "7"                         , "All I want for Christmas", "2/13" , "rabbit"                                                                                                                                                            , "1 (Karthik Bharathala)", 1      UNION
   SELECT "4/19/2019 22:14:13", 88          , "rose"                                         , "seven"                     , "All I want for Christmas", "10/22", "panda"                                                                                                                                                             , "8 (Jade Singh)", 1      UNION
   SELECT "4/19/2019 22:15:44", 18          , "pink"                                         , "7"                         , "All I want for Christmas", "2/18" , "direwolf"                                                                                                                                                          , "5 (Chae Park)", 31     UNION
   SELECT "4/19/2019 22:15:51", 5           , "blue"                                         , "7"                         , "All Star"               , "6/23" , "cat"                                                                                                                                                               , "4 (Chae Park)", 34     UNION
   SELECT "4/19/2019 22:16:02", 48          , "purple"                                      , "Choose this option instead", "All Star"               , "11/11", "dragon"                                                                                                                                                            , "6 (Rachel De Jaen catsits)", 2      UNION
   SELECT "4/19/2019 22:17:39", 42          , "crimson red"                                  , "7"                         , "Crab Rave"              , "2/11" , "dan garcia, cs animal"                                                                                                                                             , "5 (Chae Park)", 1      UNION
   SELECT "4/19/2019 22:19:26", 2           , "dark blue"                                    , "You're not the boss of me!", "All Star"               , "3/1"  , "snek"                                                                                                                                                             , "7 (Kevin Yu)", 45     UNION
   SELECT "4/19/2019 22:20:56", 21          , "blue"                                         , "Choose this option instead", "All Star"               , "4/20" , "great white shark"                                                                                                                                                 , "7 (Kevin Yu)", 1      UNION
   SELECT "4/19/2019 22:21:05", 66          , "purple"                                       , "7"                         , "All I want for Christmas", "1/1"  , "corgi"                                                                                                                                                             , "4 (Chae Park)", 1      UNION
   SELECT "4/19/2019 22:21:44", 7           , "blue"                                         , "You're not the boss of me!", "Never gonna give you up", "7/9"  , "capybara"                                                                                                                                                          , "9 (Jacqueline Tiffany Yeung)", 9      UNION
   SELECT "4/19/2019 22:24:13", 17          , "blue"                                         , "seven"                     , "Shelter"                , "11/25", "fennec fox"                                                                                                                                                        , "1 (Karthik Bharathala)", 37     UNION
   SELECT "4/19/2019 22:31:22", 99          , "purple"                                       , "7"                         , "All Star"               , "2/15" , "dolphin"                                                                                                                                                           , "5 (Chae Park)", 22     UNION
   SELECT "4/19/2019 22:33:29", 79          , "green"                                        , "7"                         , "All Star"               , "10/10", "baby goat"                                                                                                                                                         , "1 (Karthik Bharathala)", 55     UNION
   SELECT "4/19/2019 22:34:49", 69          , "红色"                                           , "You're not the boss of me!", "All Star"               , "2/29" , "joe broder uwu"                                                                                                                                                    , "5 (Chae Park)", 11     UNION
   SELECT "4/19/2019 22:35:04", 77          , "blue"                                         , "7"                         , "All I want for Christmas", "6/1"  , "dog"                                                                                                                                                               , "1 (Karthik Bharathala)", 1      UNION
   SELECT "4/19/2019 22:35:08", 9           , "black"                                        , "the number 7 below."       , "All I want for Christmas", "2/10" , "dog"                                                                                                                                                               , "1 (Karthik Bharathala)", 7      UNION
   SELECT "4/19/2019 22:39:29", 14          , "red"                                          , "7"                         , "All I want for Christmas", "7/30" , "guinea pig"                                                                                                                                                        , "5 (Chae Park)", 12     UNION
   SELECT "4/19/2019 22:41:50", 24          , "blue"                                         , "the number 7 below."       , "All I want for Christmas", "9/24" , "dog"                                                                                                                                                               , "3 (Tim Foster)", 1      UNION
   SELECT "4/19/2019 22:42:11", 88          , "orange"                                       , "7"                         , "All I want for Christmas", "1/1"  , "pig"                                                                                                                                                               , "2 (Rachel De Jaen)", 31     UNION
   SELECT "4/19/2019 22:47:51", 7           , "blue"                                         , "Choose this option instead", "Never gonna give you up", "11/21", "nothing"                                                                                                                                                           , "9 (Jacqueline Tiffany Yeung)", 1      UNION
   SELECT "4/19/2019 22:48:08", 4           , "maroon"                                       , "7"                         , "All I want for Christmas", "5/22" , "cat"                                                                                                                                                               , "2 (Rachel De Jaen)", 1      UNION
   SELECT "4/19/2019 22:50:35", 81          , "chartreuse"                                   , "the number 7 below."       , "All Star"               , "2/29" , "giraffe"                                                                                                                                                           , "1 (Karthik Bharathala)", 1      UNION
   SELECT "4/19/2019 22:52:25", 100         , "purple"                                       , "You're not the boss of me!", "Never gonna give you up", "7/2"  , "elephant"                                                                                                                                                          , "5 (Chae Park)", 1      UNION
   SELECT "4/19/2019 22:53:37", 10          , "blue"                                         , "7"                         , "All I want for Christmas", "7/3"  , "dog"                                                                                                                                                               , "8 (Jade Singh)", 22     UNION
   SELECT "4/19/2019 22:57:01", 69.420666   , "yes"                                          , "You're not the boss of me!", "All I want for Christmas", "4/20" , "a banana"                                                                                                                                                          , "6 (Rachel De Jaen catsits)", 6      UNION
   SELECT "4/19/2019 22:58:22", 69.420666   , "white"                                        , "seven"                     , "Crab Rave"              , "4/20" , "cat :)"                                                                                                                                                            , "2 (Rachel De Jaen)", 14     UNION
   SELECT "4/19/2019 23:05:24", 1           , "black"                                        , "the number 7 below."       , "Crab Rave"              , "4/20" , "cat"                                                                                                                                                               , "6 (Rachel De Jaen catsits)", 58     UNION
   SELECT "4/19/2019 23:05:55", 17          , "pink"                                         , "7"                         , "Shelter"                , "7/6"  , "dog"                                                                                                                                                               , "4 (Chae Park)", 37     UNION
   SELECT "4/19/2019 23:11:13", 1           , "black"                                        , "the number 7 below."       , "Crab Rave"              , "1/1"  , "falcon"                                                                                                                                                            , "6 (Rachel De Jaen catsits)", 4      UNION
   SELECT "4/19/2019 23:13:17", 3.1415926   , "--"                                          , "the number 7 below."       , "Never gonna give you up", "2/29" , "my scheme interpreter"                                                                                                                                             , "6 (Rachel De Jaen catsits)", 15     UNION
   SELECT "4/19/2019 23:23:36", 21          , "olive"                                        , "seven"                     , "All I want for Christmas", "7/23" , "panda"                                                                                                                                                             , "4 (Chae Park)", 1      UNION
   SELECT "4/19/2019 23:23:42", 87          , "blue raspberry"                               , "the number 7 below."       , "Never gonna give you up", "4/1"  , "horse"                                                                                                                                                             , "2 (Rachel De Jaen)", 14     UNION
   SELECT "4/19/2019 23:25:11", 69.42069421 , "yes"                                          , "seven"                     , "Never gonna give you up", "2/29" , "anime catgirl waifu"                                                                                                                                               , "4 (Chae Park)", 9      UNION
   SELECT "4/19/2019 23:26:06", 71          , "purple"                                       , "7"                         , "Shelter"                , "6/25" , "quokka"                                                                                                                                                            , "4 (Chae Park)", 21     UNION
   SELECT "4/19/2019 23:26:49", 19          , "blue"                                         , "the number 7 below."       , "All I want for Christmas", "6/4"  , "baby elephant"                                                                                                                                                     , "4 (Chae Park)", 1      UNION
   SELECT "4/19/2019 23:27:25", 77          , "orange"                                       , "the number 7 below."       , "Crab Rave"              , "1/26" , "toucan"                                                                                                                                                            , "7 (Kevin Yu)", 11     UNION
   SELECT "4/19/2019 23:34:52", 7           , "blue"                                         , "Choose this option instead", "All Star"               , "2/1"  , "dog"                                                                                                                                                               , "1 (Karthik Bharathala)", 41     UNION
   SELECT "4/19/2019 23:35:38", 33          , "turquoise"                                   , "the number 7 below."       , "Never gonna give you up", "6/6"  , "llama"                                                                                                                                                             , "5 (Chae Park)", 4      UNION
   SELECT "4/19/2019 23:49:42", 5           , "blue"                                         , "7"                         , "All Star"               , "4/26" , "emperor tamarin"                                                                                                                                                   , "7 (Kevin Yu)", 68     UNION
   SELECT "4/19/2019 23:50:06", 13          , "blue"                                         , "7"                         , "All Star"               , "4/20" , "red panda"                                                                                                                                                         , "3 (Tim Foster)", 13     UNION
   SELECT "4/19/2019 23:55:08", 3.1415926   , "pink"                                         , "the number 7 below."       , "All Star"               , "11/11", "panda"                                                                                                                                                             , "4 (Chae Park)", 3      UNION
   SELECT "4/20/2019 0:01:27" , 2           , "blue"                                         , "7"                         , "All I want for Christmas", "1/1"  , "koala"                                                                                                                                                             , "5 (Chae Park)", 1      UNION
   SELECT "4/20/2019 0:09:29" , 69          , "aqua marine"                                  , "seven"                     , "Shelter"                , "4/20" , "hedgehog"                                                                                                                                                          , "2 (Rachel De Jaen)", 75     UNION
   SELECT "4/20/2019 0:12:27" , 22          , "pink"                                         , "the number 7 below."       , "All I want for Christmas", "6/4"  , "elephant"                                                                                                                                                          , "5 (Chae Park)", 11     UNION
   SELECT "4/20/2019 0:14:23" , 73          , "gray"                                         , "7"                         , "Shelter"                , "4/20" , "panther"                                                                                                                                                           , "4 (Chae Park)", 1      UNION
   SELECT "4/20/2019 0:17:46" , 12          , "blue"                                         , "the number 7 below."       , "Never gonna give you up", "1/1"  , "bear"                                                                                                                                                              , "9 (Jacqueline Tiffany Yeung)", 17     UNION
   SELECT "4/20/2019 0:18:13" , 88          , "shhh keep it a secret"                        , "Choose this option instead", "Shelter"                , "8/8"  , "a giant robot bear that knows python really well"                                                                                                                  , "5 (Chae Park)", 15     UNION
   SELECT "4/20/2019 0:27:37" , 56          , "blue"                                         , "the number 7 below."       , "Shelter"                , "1/1"  , "mickey piekarski"                                                                                                                                                 , "7 (Kevin Yu)", 3      UNION
   SELECT "4/20/2019 0:33:05" , 17          , "blue"                                         , "the number 7 below."       , "All I want for Christmas", "5/30" , "dog"                                                                                                                                                               , "3 (Tim Foster)", 32     UNION
   SELECT "4/20/2019 1:03:58" , 7           , "pink"                                         , "the number 7 below."       , "All Star"               , "5/18" , "fish"                                                                                                                                                              , "1 (Karthik Bharathala)", 23     UNION
   SELECT "4/20/2019 1:26:09" , 45          , "blue"                                         , "Choose this option instead", "Crab Rave"              , "4/20" , "dog"                                                                                                                                                               , "1 (Karthik Bharathala)", 19     UNION
   SELECT "4/20/2019 1:31:41" , 10          , "white"                                        , "7"                         , "All I want for Christmas", "10/16", "dog"                                                                                                                                                               , "4 (Chae Park)", 1      UNION
   SELECT "4/20/2019 1:34:38" , 42          , "red"                                          , "7"                         , "Big enough"             , "11/24", "dragon"                                                                                                                                                            , "4 (Chae Park)", 19     UNION
   SELECT "4/20/2019 2:01:40" , 23          , "turquoise"                                    , "Choose this option instead", "Crab Rave"              , "10/26", "yorkie and shih tzu"                                                                                                                                               , "1 (Karthik Bharathala)", 1      UNION
   SELECT "4/20/2019 8:29:53" , 16          , "orange"                                       , "the number 7 below."       , "Shelter"                , "10/8" , "ocelot"                                                                                                                                                            , "4 (Chae Park)", 29     UNION
   SELECT "4/20/2019 8:36:24" , 73          , "blue"                                        , "7"                         , "All Star"               , "3/21" , "dolphin"                                                                                                                                                          , "7 (Kevin Yu)", 1      UNION
   SELECT "4/20/2019 8:48:04" , 6           , "green"                                        , "7"                         , "All I want for Christmas", "4/20" , "baby elephant"                                                                                                                                                     , "5 (Chae Park)", 1      UNION
   SELECT "4/20/2019 8:52:07" , 12          , "light blue"                                  , "the number 7 below."       , "All Star"               , "4/20" , "hedgehog"                                                                                                                                                         , "9 (Jacqueline Tiffany Yeung)", 1      UNION
   SELECT "4/20/2019 8:54:20" , 7           , "blue"                                         , "7"                         , "All Star"               , "8/12" , "bunny or monkey"                                                                                                                                                   , "1 (Karthik Bharathala)", 1      UNION
   SELECT "4/20/2019 9:07:53" , 17          , "navy blue"                                    , "the number 7 below."       , "Crab Rave"              , "4/20" , "cat"                                                                                                                                                               , "6 (Rachel De Jaen catsits)", 11     UNION
   SELECT "4/20/2019 9:21:32" , 99          , "artisan color"                                , "7"                         , "Never gonna give you up", "1/1"  , "cat"                                                                                                                                                               , "4 (Chae Park)", 37     UNION
   SELECT "4/20/2019 9:21:41" , 33          , "white"                                        , "7"                         , "Crab Rave"              , "9/13" , "cyber-dolphin"                                                                                                                                                     , "4 (Chae Park)", 1      UNION
   SELECT "4/20/2019 9:29:55" , 26          , "blue"                                         , "7"                         , "All I want for Christmas", "4/16" , "a goat"                                                                                                                                                            , "1 (Karthik Bharathala)", 1      UNION
   SELECT "4/20/2019 9:45:20" , 20          , "blue"                                         , "the number 7 below."       , "All I want for Christmas", "4/20" , "lion"                                                                                                                                                              , "2 (Rachel De Jaen)", 1      UNION
   SELECT "4/20/2019 9:47:59" , 25          , "blue"                                         , "7"                         , "All I want for Christmas", "1/1"  , "panda"                                                                                                                                                             , "5 (Chae Park)", 1      UNION
   SELECT "4/20/2019 9:51:02" , 8           , "blue"                                         , "7"                         , "All I want for Christmas", "5/15" , "red panda"                                                                                                                                                         , "1 (Karthik Bharathala)", 1      UNION
   SELECT "4/20/2019 9:53:20" , 16          , "purple"                                       , "7"                         , "All I want for Christmas", "4/20" , "an elephant"                                                                                                                                                       , "4 (Chae Park)", 101    UNION
   SELECT "4/20/2019 10:01:25", 7           , "green"                                       , "Choose this option instead", "Never gonna give you up", "4/10" , "a dog"                                                                                                                                                            , "5 (Chae Park)", 2      UNION
   SELECT "4/20/2019 10:02:49", 16          , "pink"                                         , "the number 7 below."       , "All Star"               , "4/29" , "panda"                                                                                                                                                             , "8 (Jade Singh)", 1      UNION
   SELECT "4/20/2019 10:16:15", 45          , "blue"                                        , "the number 7 below."       , "All I want for Christmas", "12/24", "owl"                                                                                                                                                               , "5 (Chae Park)", 2      UNION
   SELECT "4/20/2019 10:16:39", 1.618033989 , "black"                                        , "7"                         , "All I want for Christmas", "4/30" , "tarantula"                                                                                                                                                         , "6 (Rachel De Jaen catsits)", 23     UNION
   SELECT "4/20/2019 10:26:38", 27          , "blue"                                         , "Choose this option instead", "All Star"               , "6/29" , "dog"                                                                                                                                                               , "9 (Jacqueline Tiffany Yeung)", 4      UNION
   SELECT "4/20/2019 11:01:58", 66          , "deep blue"                                    , "Choose this option instead", "All Star"               , "7/23" , "caribou"                                                                                                                                                           , "5 (Chae Park)", 87     UNION
   SELECT "4/20/2019 11:09:56", 55          , "blue"                                         , "You're not the boss of me!", "Crab Rave"              , "1/1"  , "panda"                                                                                                                                                             , "1 (Karthik Bharathala)", 5      UNION
   SELECT "4/20/2019 11:09:57", 7           , "red"                                          , "7"                         , "Big enough"             , "12/31", "cat"                                                                                                                                                               , "1 (Karthik Bharathala)", 3      UNION
   SELECT "4/20/2019 11:11:25", 8           , "yellow"                                       , "7"                         , "Shelter"                , "9/14" , "a bird"                                                                                                                                                            , "9 (Jacqueline Tiffany Yeung)", 34     UNION
   SELECT "4/20/2019 11:28:31", 9           , "green"                                        , "7"                         , "All I want for Christmas", "12/9" , "kangaroo"                                                                                                                                                          , "4 (Chae Park)", 1      UNION
   SELECT "4/20/2019 11:35:28", 61          , "purple"                                       , "7"                         , "All Star"               , "12/25", "dingo"                                                                                                                                                             , "3 (Tim Foster)", 1      UNION
   SELECT "4/20/2019 11:53:34", 6           , "green"                                        , "the number 7 below."       , "All Star"               , "11/11", "cat"                                                                                                                                                               , "4 (Chae Park)", 1      UNION
   SELECT "4/20/2019 11:54:11", 99          , "yellow"                                       , "Choose this option instead", "All I want for Christmas", "12/24", "eagle"                                                                                                                                                             , "9 (Jacqueline Tiffany Yeung)", 1      UNION
   SELECT "4/20/2019 11:58:57", 74          , "blue"                                         , "the number 7 below."       , "Never gonna give you up", "7/4"  , "cheddar the corgi from b99"                                                                                                                                        , "5 (Chae Park)", 23     UNION
   SELECT "4/20/2019 12:30:17", 3           , "red"                                          , "the number 7 below."       , "Never gonna give you up", "12/25", "quokka"                                                                                                                                                            , "7 (Kevin Yu)", 97     UNION
   SELECT "4/20/2019 12:31:18", 7           , "blue"                                         , "7"                         , "All I want for Christmas", "4/20" , "chinese pastoral dog"                                                                                                                                             , "4 (Chae Park)", 1      UNION
   SELECT "4/20/2019 12:54:42", 29          , "blue"                                         , "the number 7 below."       , "All Star"               , "5/29" , "dog"                                                                                                                                                               , "7 (Kevin Yu)", 53     UNION
   SELECT "4/20/2019 13:07:39", 18          , "black"                                        , "7"                         , "All I want for Christmas", "12/18", "cat"                                                                                                                                                               , "4 (Chae Park)", 11     UNION
   SELECT "4/20/2019 13:14:47", 69          , "nude"                                         , "the number 7 below."       , "All Star"               , "6/9"  , "my dog because i love him."                                                                                                                                        , "6 (Rachel De Jaen catsits)", 1      UNION
   SELECT "4/20/2019 13:33:19", 15          , "blue"                                         , "the number 7 below."       , "All I want for Christmas", "8/16" , "peacock"                                                                                                                                                           , "4 (Chae Park)", 1      UNION
   SELECT "4/20/2019 13:46:16", 12          , "blue"                                         , "7"                         , "Never gonna give you up", "10/12", "cat"                                                                                                                                                               , "6 (Rachel De Jaen catsits)", 19     UNION
   SELECT "4/20/2019 13:52:45", 88          , "blue"                                         , "the number 7 below."       , "All Star"               , "8/11" , "elephant"                                                                                                                                                          , "4 (Chae Park)", 23     UNION
   SELECT "4/20/2019 14:01:18", 13          , "blue"                                         , "7"                         , "All I want for Christmas", "6/6"  , "cat"                                                                                                                                                               , "6 (Rachel De Jaen catsits)", 1      UNION
   SELECT "4/20/2019 14:34:55", 17          , "blue"                                         , "You're not the boss of me!", "Never gonna give you up", "10/1" , "dolphin"                                                                                                                                                           , "7 (Kevin Yu)", 17     UNION
   SELECT "4/20/2019 14:36:50", 7           , "blue"                                         , "Choose this option instead", "Shelter"                , "12/25", "cat"                                                                                                                                                               , "4 (Chae Park)", 1      UNION
   SELECT "4/20/2019 14:43:04", 27          , "turquoise"                                    , "the number 7 below."       , "Never gonna give you up", "3/17" , "penguin"                                                                                                                                                           , "4 (Chae Park)", 3      UNION
   SELECT "4/20/2019 15:02:33", 1           , "black"                                        , "the number 7 below."       , "All I want for Christmas", "9/13" , "python"                                                                                                                                                            , "6 (Rachel De Jaen catsits)", 1      UNION
   SELECT "4/20/2019 15:03:43", 13          , "maroon"                                       , "7"                         , "All I want for Christmas", "9/13" , "teacup pig"                                                                                                                                                        , "3 (Tim Foster)", 7      UNION
   SELECT "4/20/2019 15:09:12", 71          , "red"                                          , "the number 7 below."       , "All I want for Christmas", "7/1"  , "cat"                                                                                                                                                               , "7 (Kevin Yu)", 1      UNION
   SELECT "4/20/2019 15:28:57", 14          , "yellow"                                       , "7"                         , "All I want for Christmas", "5/21" , "cat"                                                                                                                                                               , "6 (Rachel De Jaen catsits)", 7      UNION
   SELECT "4/20/2019 16:22:09", 7           , "blue"                                         , "7"                         , "Shelter"                , "5/12" , "7"                                                                                                                                                                 , "6 (Rachel De Jaen catsits)", 31     UNION
   SELECT "4/20/2019 16:49:09", 69          , "black"                                        , "the number 7 below."       , "All I want for Christmas", "3/19" , "ryan koh"                                                                                                                                                          , "5 (Chae Park)", 1      UNION
   SELECT "4/20/2019 16:54:06", 13          , "purple"                                       , "7"                         , "All I want for Christmas", "5/13" , "alpaca"                                                                                                                                                            , "1 (Karthik Bharathala)", 13     UNION
   SELECT "4/20/2019 17:00:35", 37          , "pink"                                         , "7"                         , "Never gonna give you up", "4/2"  , "teacup pig"                                                                                                                                                        , "7 (Kevin Yu)", 50     UNION
   SELECT "4/20/2019 17:01:43", 2           , "black"                                        , "the number 7 below."       , "All I want for Christmas", "2/17" , "chae park's dog"                                                                                                                                                  , "4 (Chae Park)", 100    UNION
   SELECT "4/20/2019 17:12:14", 7           , "red"                                          , "Choose this option instead", "All I want for Christmas", "1/7"  , "cats!!!!!"                                                                                                                                                         , "2 (Rachel De Jaen)", 3      UNION
   SELECT "4/20/2019 17:24:01", 36          , "blue"                                         , "Choose this option instead", "All I want for Christmas", "1/1"  , "majestic stallion"                                                                                                                                                 , "5 (Chae Park)", 1      UNION
   SELECT "4/20/2019 17:55:00", 25          , "blue"                                         , "7"                         , "Shelter"                , "2/29" , "red panda"                                                                                                                                                         , "1 (Karthik Bharathala)", 325    UNION
   SELECT "4/20/2019 18:19:42", 13          , "red"                                          , "You're not the boss of me!", "All I want for Christmas", "5/7"  , "none"                                                                                                                                                              , "1 (Karthik Bharathala)", 4      UNION
   SELECT "4/20/2019 18:38:51", 16          , "light blue"                                  , "the number 7 below."       , "All I want for Christmas", "9/16" , "a unicorn"                                                                                                                                                         , "5 (Chae Park)", 39     UNION
   SELECT "4/20/2019 19:37:14", 12          , "blue"                                         , "7"                         , "All I want for Christmas", "9/20" , "hedgehog"                                                                                                                                                          , "5 (Chae Park)", 22     UNION
   SELECT "4/20/2019 19:49:13", 81          , "black"                                        , "seven"                     , "All I want for Christmas", "2/29" , "dragon"                                                                                                                                                            , "1 (Karthik Bharathala)", 1000   UNION
   SELECT "4/20/2019 21:15:23", 69          , "purple"                                       , "the number 7 below."       , "Shelter"                , "4/20" , "toy poodle"                                                                                                                                                        , "1 (Karthik Bharathala)", 10101  UNION
   SELECT "4/20/2019 21:23:13", 1           , "black"                                        , "7"                         , "All Star"               , "4/3"  , "dog"                                                                                                                                                               , "3 (Tim Foster)", 1      UNION
   SELECT "4/20/2019 22:31:09", 3           , "blue"                                         , "the number 7 below."       , "Shelter"                , "9/19" , "a cat im not allergic to"                                                                                                                                          , "4 (Chae Park)", 10     UNION
   SELECT "4/20/2019 22:31:19", 45          , "green"                                        , "7"                         , "All Star"               , "5/17" , "dog"                                                                                                                                                               , "3 (Tim Foster)", 2      UNION
   SELECT "4/20/2019 22:54:14", 100         , "rose pink"                                    , "7"                         , "All I want for Christmas", "5/5"  , "dragon"                                                                                                                                                            , "1 (Karthik Bharathala)", 2      UNION
   SELECT "4/20/2019 23:27:05", 8           , "green"                                        , "7"                         , "All I want for Christmas", "5/12" , "a cat"                                                                                                                                                             , "4 (Chae Park)", 9      UNION
   SELECT "4/20/2019 23:31:54", 14          , "yellow"                                       , "7"                         , "All Star"               , "11/24", "pupper"                                                                                                                                                            , "1 (Karthik Bharathala)", 14     UNION
   SELECT "4/20/2019 23:40:35", 33          , "emerald green"                                , "You're not the boss of me!", "All Star"               , "1/5"  , "a dragon"                                                                                                                                                          , "5 (Chae Park)", 1      UNION
   SELECT "4/20/2019 23:43:33", 2           , "white"                                        , "Choose this option instead", "All I want for Christmas", "1/1"  , "old cat"                                                                                                                                                           , "4 (Chae Park)", 1      ;

CREATE TABLE checkboxes AS
   SELECT "4/19/2019 21:47:40" AS time, "True" AS "0", "True" AS "1", "True" AS "2", "True" AS "3", "True" AS "4", "True" AS "5", "True" AS "6", "True" AS "7", "True" AS "8", "True" AS "9", "True" AS "10", "True" AS "2018", "True" AS "9000", "True" AS "9001" UNION
   SELECT "4/19/2019 21:47:41", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/19/2019 21:47:43", "True" , "True" , "True" , "False", "False", "True" , "False", "False", "False", "False", "False", "False", "True" , "True"  UNION
   SELECT "4/19/2019 21:48:11", "True" , "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "4/19/2019 21:48:30", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 21:49:08", "True" , "False", "False", "True" , "False", "False", "True" , "False", "False", "True" , "False", "False", "True" , "False" UNION
   SELECT "4/19/2019 21:49:11", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "4/19/2019 21:49:21", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "4/19/2019 21:49:22", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/19/2019 21:49:27", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 21:49:36", "True" , "True" , "False", "False", "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "True"  UNION
   SELECT "4/19/2019 21:49:37", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "True" , "False", "True"  UNION
   SELECT "4/19/2019 21:50:09", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 21:50:39", "False", "True" , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "True"  UNION
   SELECT "4/19/2019 21:50:40", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "False" UNION
   SELECT "4/19/2019 21:51:42", "True" , "True" , "True" , "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/19/2019 21:52:00", "False", "True" , "False", "False", "False", "True" , "False", "False", "True" , "True" , "False", "True" , "False", "True"  UNION
   SELECT "4/19/2019 21:52:12", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "4/19/2019 21:52:42", "False", "False", "False", "True" , "False", "False", "True" , "True" , "False", "True" , "False", "False", "False", "False" UNION
   SELECT "4/19/2019 21:53:19", "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "True"  UNION
   SELECT "4/19/2019 21:53:27", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 21:53:43", "False", "True" , "True" , "False", "False", "True" , "False", "True" , "False", "True" , "False", "False", "False", "False" UNION
   SELECT "4/19/2019 21:54:41", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "True" , "False", "True"  UNION
   SELECT "4/19/2019 21:55:22", "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 21:55:54", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "4/19/2019 21:56:03", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 21:57:11", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:00:04", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 22:00:36", "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 22:01:07", "False", "False", "False", "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 22:01:30", "False", "False", "True" , "False", "True" , "False", "False", "False", "True" , "True" , "False", "True" , "True" , "False" UNION
   SELECT "4/19/2019 22:01:50", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "True" , "False", "False" UNION
   SELECT "4/19/2019 22:02:30", "True" , "False", "True" , "False", "True" , "False", "False", "False", "True" , "False", "False", "True" , "False", "True"  UNION
   SELECT "4/19/2019 22:02:32", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:03:16", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "4/19/2019 22:04:06", "False", "True" , "False", "True" , "False", "False", "False", "True" , "True" , "False", "True" , "True" , "False", "True"  UNION
   SELECT "4/19/2019 22:05:19", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:06:09", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 22:08:27", "True" , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/19/2019 22:09:19", "True" , "False", "True" , "True" , "False", "True" , "False", "False", "False", "True" , "False", "False", "False", "True"  UNION
   SELECT "4/19/2019 22:09:49", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False", "False", "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:10:30", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "True" , "True" , "False" UNION
   SELECT "4/19/2019 22:11:54", "True" , "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "True" , "False", "True" , "False" UNION
   SELECT "4/19/2019 22:13:03", "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:13:07", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:14:13", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 22:15:44", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 22:15:51", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 22:16:02", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:17:39", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:19:26", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:20:56", "True" , "True" , "False", "True" , "False", "False", "True" , "False", "False", "True" , "True" , "False", "True" , "True"  UNION
   SELECT "4/19/2019 22:21:05", "False", "True" , "False", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:21:44", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:24:13", "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "4/19/2019 22:31:22", "True" , "True" , "False", "False", "False", "True" , "False", "False", "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:33:29", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 22:34:49", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 22:35:04", "True" , "True" , "True" , "True" , "False", "False", "False", "False", "False", "False", "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:35:08", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 22:39:29", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False" UNION
   SELECT "4/19/2019 22:41:50", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False" UNION
   SELECT "4/19/2019 22:42:11", "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "4/19/2019 22:47:51", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:48:08", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:50:35", "False", "True" , "False", "True" , "True" , "True" , "False", "False", "False", "False", "True" , "False", "False", "True"  UNION
   SELECT "4/19/2019 22:52:25", "True" , "True" , "True" , "False", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 22:53:37", "True" , "True" , "True" , "True" , "False", "False", "True" , "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 22:57:01", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "4/19/2019 22:58:22", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 23:05:24", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 23:05:55", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/19/2019 23:11:13", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 23:13:17", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 23:23:36", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/19/2019 23:23:42", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "True"  UNION
   SELECT "4/19/2019 23:25:11", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 23:26:06", "False", "True" , "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "True" , "False", "False" UNION
   SELECT "4/19/2019 23:26:49", "False", "True" , "False", "True" , "False", "False", "True" , "False", "False", "True" , "False", "False", "True" , "True"  UNION
   SELECT "4/19/2019 23:27:25", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 23:34:52", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/19/2019 23:35:38", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/19/2019 23:49:42", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/19/2019 23:50:06", "True" , "True" , "True" , "True" , "False", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/19/2019 23:55:08", "False", "False", "False", "True" , "False", "True" , "True" , "True" , "False", "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/20/2019 0:01:27" , "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/20/2019 0:09:29" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/20/2019 0:12:27" , "False", "True" , "True" , "False", "False", "False", "True" , "False", "True" , "True" , "True" , "False", "False", "True"  UNION
   SELECT "4/20/2019 0:14:23" , "False", "False", "True" , "False", "True" , "False", "True" , "False", "False", "False", "True" , "False", "False", "False" UNION
   SELECT "4/20/2019 0:17:46" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/20/2019 0:18:13" , "True" , "False", "False", "True" , "False", "False", "True" , "True" , "True" , "False", "True" , "True" , "True" , "True"  UNION
   SELECT "4/20/2019 0:27:37" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/20/2019 0:33:05" , "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False" UNION
   SELECT "4/20/2019 1:03:58" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "4/20/2019 1:26:09" , "False", "False", "True" , "True" , "False", "False", "False", "False", "True" , "False", "True" , "False", "True" , "True"  UNION
   SELECT "4/20/2019 1:31:41" , "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "True"  UNION
   SELECT "4/20/2019 1:34:38" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "4/20/2019 2:01:40" , "False", "True" , "False", "True" , "False", "True" , "True" , "False", "True" , "False", "True" , "True" , "True" , "True"  UNION
   SELECT "4/20/2019 8:29:53" , "True" , "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "True"  UNION
   SELECT "4/20/2019 8:36:24" , "False", "False", "True" , "False", "True" , "False", "True" , "True" , "True" , "False", "False", "True" , "False", "False" UNION
   SELECT "4/20/2019 8:48:04" , "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "True" , "True" , "False" UNION
   SELECT "4/20/2019 8:52:07" , "False", "False", "True" , "True" , "True" , "False", "False", "False", "False", "True" , "False", "False", "True" , "False" UNION
   SELECT "4/20/2019 8:54:20" , "False", "False", "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "False", "False", "False" UNION
   SELECT "4/20/2019 9:07:53" , "False", "False", "True" , "False", "False", "False", "False", "True" , "False", "True" , "False", "True" , "False", "True"  UNION
   SELECT "4/20/2019 9:21:32" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "True" , "False" UNION
   SELECT "4/20/2019 9:21:41" , "True" , "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/20/2019 9:29:55" , "False", "False", "True" , "True" , "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/20/2019 9:45:20" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/20/2019 9:47:59" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "True" , "False", "False" UNION
   SELECT "4/20/2019 9:51:02" , "False", "False", "True" , "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "True"  UNION
   SELECT "4/20/2019 9:53:20" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "False", "False" UNION
   SELECT "4/20/2019 10:01:25", "False", "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "4/20/2019 10:02:49", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "True" , "False" UNION
   SELECT "4/20/2019 10:16:15", "True" , "True" , "False", "True" , "True" , "False", "False", "False", "False", "True" , "True" , "False", "True" , "True"  UNION
   SELECT "4/20/2019 10:16:39", "True" , "True" , "True" , "False", "True" , "False", "False", "False", "True" , "False", "False", "True" , "False", "False" UNION
   SELECT "4/20/2019 10:26:38", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False" UNION
   SELECT "4/20/2019 11:01:58", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "True"  UNION
   SELECT "4/20/2019 11:09:56", "True" , "False", "False", "False", "True" , "True" , "True" , "False", "True" , "False", "True" , "True" , "True" , "False" UNION
   SELECT "4/20/2019 11:09:57", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/20/2019 11:11:25", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False" UNION
   SELECT "4/20/2019 11:28:31", "False", "True" , "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "False", "True" , "False" UNION
   SELECT "4/20/2019 11:35:28", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/20/2019 11:53:34", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/20/2019 11:54:11", "True" , "True" , "True" , "True" , "False", "False", "True" , "False", "False", "True" , "True" , "True" , "True" , "False" UNION
   SELECT "4/20/2019 11:58:57", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "True" , "False", "False" UNION
   SELECT "4/20/2019 12:30:17", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/20/2019 12:31:18", "True" , "False", "False", "False", "True" , "True" , "False", "False", "False", "False", "False", "True" , "True" , "False" UNION
   SELECT "4/20/2019 12:54:42", "True" , "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "True" , "True" , "False", "False" UNION
   SELECT "4/20/2019 13:07:39", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/20/2019 13:14:47", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "True"  UNION
   SELECT "4/20/2019 13:33:19", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "False", "False" UNION
   SELECT "4/20/2019 13:46:16", "True" , "False", "False", "True" , "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "True"  UNION
   SELECT "4/20/2019 13:52:45", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False" UNION
   SELECT "4/20/2019 14:01:18", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "4/20/2019 14:34:55", "False", "False", "True" , "True" , "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/20/2019 14:36:50", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "False", "False" UNION
   SELECT "4/20/2019 14:43:04", "True" , "False", "True" , "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "False" UNION
   SELECT "4/20/2019 15:02:33", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "4/20/2019 15:03:43", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/20/2019 15:09:12", "False", "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "True"  UNION
   SELECT "4/20/2019 15:28:57", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/20/2019 16:22:09", "True" , "False", "False", "True" , "True" , "False", "True" , "False", "False", "False", "True" , "True" , "False", "True"  UNION
   SELECT "4/20/2019 16:49:09", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "4/20/2019 16:54:06", "True" , "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "True" , "False" UNION
   SELECT "4/20/2019 17:00:35", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "True"  UNION
   SELECT "4/20/2019 17:01:43", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "True" , "True" , "False" UNION
   SELECT "4/20/2019 17:12:14", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "True"  UNION
   SELECT "4/20/2019 17:24:01", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "True" , "True"  UNION
   SELECT "4/20/2019 17:55:00", "True" , "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/20/2019 18:19:42", "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "True" , "True" , "False", "False", "False" UNION
   SELECT "4/20/2019 18:38:51", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "False", "False", "True" , "True"  UNION
   SELECT "4/20/2019 19:37:14", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "4/20/2019 19:49:13", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "True" , "True"  UNION
   SELECT "4/20/2019 21:15:23", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "4/20/2019 21:23:13", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "4/20/2019 22:31:09", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/20/2019 22:31:19", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "False" UNION
   SELECT "4/20/2019 22:54:14", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "4/20/2019 23:27:05", "True" , "False", "False", "True" , "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "True"  UNION
   SELECT "4/20/2019 23:31:54", "True" , "True" , "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "True" , "False", "True"  UNION
   SELECT "4/20/2019 23:40:35", "False", "False", "True" , "False", "False", "True" , "False", "True" , "True" , "False", "False", "True" , "False", "True"  UNION
   SELECT "4/20/2019 23:43:33", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" ;

`;
